<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>TlarcRosBridge.Infrastructure</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <!-- <PackageReference Include="Rcl.NET" Version="1.4.0"/>
        <PackageReference Include="Rosidl.Runtime" Version="1.4.0"/> -->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kernel\Kernel.Contract\Kernel.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Rcl.NET" Version="2.0.0-preview.1" />
    </ItemGroup>

</Project>
