
<Project>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <InvariantGlobalization>true</InvariantGlobalization>
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>
</Project>