<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
        
        <InvariantGlobalization>true</InvariantGlobalization>
        <OptimizationPreference>Speed</OptimizationPreference>
        
        <UseRidGraph>true</UseRidGraph>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        
        <PublishDir>$(SolutionDir)\.test\Test\$(ProjectName)\$(Configuration)</PublishDir>

        <!-- <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile> -->

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>


    <ItemGroup><!-- <ProjectReference Include="path\to\your.csproj"/> -->
    
      <ProjectReference Include="..\ALPlanner.Infrastructure\ALPlanner.Infrastructure.csproj" />
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="alglib.net.simd" Version="3.19.0" />
      <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta2" />
      <PackageReference Include="NumFlat" Version="1.2.0" />
      <PackageReference Include="ScottPlot" Version="5.0.56" />
    </ItemGroup>

</Project>
