//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace Rosidl.Messages.RmcsMap
{
    /// <summary>
    /// Message interface definition for <c>rmcs_map/msg/GameStatus</c>.
    /// </summary>
    [global::Rosidl.Runtime.TypeSupportAttribute("rmcs_map/msg/GameStatus")]
    public unsafe partial class GameStatus : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static string TypeSupportName => "rmcs_map/msg/GameStatus";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__rmcs_map__msg__GameStatus")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="GameStatus"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='friendsHero'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_hero]]></c>
        /// </param>
        /// <param name='friendsEngineer'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_engineer]]></c>
        /// </param>
        /// <param name='friendsInfantryIii'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iii]]></c>
        /// </param>
        /// <param name='friendsInfantryIv'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iv]]></c>
        /// </param>
        /// <param name='friendsInfantryV'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_v]]></c>
        /// </param>
        /// <param name='friendsSentry'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_sentry]]></c>
        /// </param>
        /// <param name='enemiesHero'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_hero]]></c>
        /// </param>
        /// <param name='enemiesEngineer'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_engineer]]></c>
        /// </param>
        /// <param name='enemiesInfantryIii'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iii]]></c>
        /// </param>
        /// <param name='enemiesInfantryIv'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iv]]></c>
        /// </param>
        /// <param name='enemiesInfantryV'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_v]]></c>
        /// </param>
        /// <param name='enemiesSentry'>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_sentry]]></c>
        /// </param>
        /// <param name='friendsOutpostHp'>
        /// Originally defined as: <c><![CDATA[int32 friends_outpost_hp]]></c>
        /// </param>
        /// <param name='enemiesOutpostHp'>
        /// Originally defined as: <c><![CDATA[int32 enemies_outpost_hp]]></c>
        /// </param>
        /// <param name='friendsBaseHp'>
        /// Originally defined as: <c><![CDATA[int32 friends_base_hp]]></c>
        /// </param>
        /// <param name='enemiesBaseHp'>
        /// Originally defined as: <c><![CDATA[int32 enemies_base_hp]]></c>
        /// </param>
        /// <param name='bullet'>
        /// Originally defined as: <c><![CDATA[int32 bullet]]></c>
        /// </param>
        /// <param name='supplyBullet'>
        /// Originally defined as: <c><![CDATA[int32 supply_bullet]]></c>
        /// </param>
        /// <param name='rfid'>
        /// Originally defined as: <c><![CDATA[int8 rfid]]></c>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public GameStatus(
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsHero = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsEngineer = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsInfantryIii = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsInfantryIv = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsInfantryV = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @friendsSentry = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesHero = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesEngineer = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesInfantryIii = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesInfantryIv = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesInfantryV = null,
            global::Rosidl.Messages.RmcsMap.RobotStatus? @enemiesSentry = null,
            int @friendsOutpostHp = 0,
            int @enemiesOutpostHp = 0,
            int @friendsBaseHp = 0,
            int @enemiesBaseHp = 0,
            int @bullet = 0,
            int @supplyBullet = 0,
            sbyte @rfid = 0
        )
        {
            FriendsHero = @friendsHero ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsEngineer = @friendsEngineer ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsInfantryIii = @friendsInfantryIii ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsInfantryIv = @friendsInfantryIv ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsInfantryV = @friendsInfantryV ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsSentry = @friendsSentry ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesHero = @enemiesHero ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesEngineer = @enemiesEngineer ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesInfantryIii = @enemiesInfantryIii ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesInfantryIv = @enemiesInfantryIv ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesInfantryV = @enemiesInfantryV ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            EnemiesSentry = @enemiesSentry ?? new global::Rosidl.Messages.RmcsMap.RobotStatus();
            FriendsOutpostHp = @friendsOutpostHp;
            EnemiesOutpostHp = @enemiesOutpostHp;
            FriendsBaseHp = @friendsBaseHp;
            EnemiesBaseHp = @enemiesBaseHp;
            Bullet = @bullet;
            SupplyBullet = @supplyBullet;
            Rfid = @rfid;
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="GameStatus"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public GameStatus(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.FriendsHero = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsHero, textEncoding);
            this.FriendsEngineer = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsEngineer, textEncoding);
            this.FriendsInfantryIii = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsInfantryIii, textEncoding);
            this.FriendsInfantryIv = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsInfantryIv, textEncoding);
            this.FriendsInfantryV = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsInfantryV, textEncoding);
            this.FriendsSentry = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.FriendsSentry, textEncoding);
            this.EnemiesHero = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesHero, textEncoding);
            this.EnemiesEngineer = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesEngineer, textEncoding);
            this.EnemiesInfantryIii = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesInfantryIii, textEncoding);
            this.EnemiesInfantryIv = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesInfantryIv, textEncoding);
            this.EnemiesInfantryV = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesInfantryV, textEncoding);
            this.EnemiesSentry = new global::Rosidl.Messages.RmcsMap.RobotStatus(in priv.EnemiesSentry, textEncoding);
            this.FriendsOutpostHp = priv.FriendsOutpostHp;
            this.EnemiesOutpostHp = priv.EnemiesOutpostHp;
            this.FriendsBaseHp = priv.FriendsBaseHp;
            this.EnemiesBaseHp = priv.EnemiesBaseHp;
            this.Bullet = priv.Bullet;
            this.SupplyBullet = priv.SupplyBullet;
            this.Rfid = priv.Rfid;
        }
        
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_hero]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsHero { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_engineer]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsEngineer { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iii]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsInfantryIii { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iv]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsInfantryIv { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_v]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsInfantryV { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_sentry]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus FriendsSentry { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_hero]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesHero { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_engineer]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesEngineer { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iii]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesInfantryIii { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iv]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesInfantryIv { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_v]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesInfantryV { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_sentry]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public global::Rosidl.Messages.RmcsMap.RobotStatus EnemiesSentry { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 friends_outpost_hp]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int FriendsOutpostHp { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 enemies_outpost_hp]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int EnemiesOutpostHp { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 friends_base_hp]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int FriendsBaseHp { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 enemies_base_hp]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int EnemiesBaseHp { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 bullet]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int Bullet { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 supply_bullet]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public int SupplyBullet { get; set; }
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int8 rfid]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public sbyte Rfid { get; set; }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.FriendsHero.WriteTo(ref priv.FriendsHero, textEncoding);
            this.FriendsEngineer.WriteTo(ref priv.FriendsEngineer, textEncoding);
            this.FriendsInfantryIii.WriteTo(ref priv.FriendsInfantryIii, textEncoding);
            this.FriendsInfantryIv.WriteTo(ref priv.FriendsInfantryIv, textEncoding);
            this.FriendsInfantryV.WriteTo(ref priv.FriendsInfantryV, textEncoding);
            this.FriendsSentry.WriteTo(ref priv.FriendsSentry, textEncoding);
            this.EnemiesHero.WriteTo(ref priv.EnemiesHero, textEncoding);
            this.EnemiesEngineer.WriteTo(ref priv.EnemiesEngineer, textEncoding);
            this.EnemiesInfantryIii.WriteTo(ref priv.EnemiesInfantryIii, textEncoding);
            this.EnemiesInfantryIv.WriteTo(ref priv.EnemiesInfantryIv, textEncoding);
            this.EnemiesInfantryV.WriteTo(ref priv.EnemiesInfantryV, textEncoding);
            this.EnemiesSentry.WriteTo(ref priv.EnemiesSentry, textEncoding);
            priv.FriendsOutpostHp = this.FriendsOutpostHp;
            priv.EnemiesOutpostHp = this.EnemiesOutpostHp;
            priv.FriendsBaseHp = this.FriendsBaseHp;
            priv.EnemiesBaseHp = this.EnemiesBaseHp;
            priv.Bullet = this.Bullet;
            priv.SupplyBullet = this.SupplyBullet;
            priv.Rfid = this.Rfid;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new GameStatus(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Blittable native structure for <c>rmcs_map/msg/GameStatus</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_hero]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsHero;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_engineer]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsEngineer;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iii]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsInfantryIii;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_iv]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsInfantryIv;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_infantry_v]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsInfantryV;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus friends_sentry]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv FriendsSentry;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_hero]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesHero;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_engineer]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesEngineer;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iii]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesInfantryIii;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_iv]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesInfantryIv;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_infantry_v]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesInfantryV;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[rmcs_map/msg/RobotStatus enemies_sentry]]></c>
            /// </summary>
            public global::Rosidl.Messages.RmcsMap.RobotStatus.Priv EnemiesSentry;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 friends_outpost_hp]]></c>
            /// </summary>
            public int FriendsOutpostHp;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 enemies_outpost_hp]]></c>
            /// </summary>
            public int EnemiesOutpostHp;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 friends_base_hp]]></c>
            /// </summary>
            public int FriendsBaseHp;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 enemies_base_hp]]></c>
            /// </summary>
            public int EnemiesBaseHp;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 bullet]]></c>
            /// </summary>
            public int Bullet;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int32 supply_bullet]]></c>
            /// </summary>
            public int SupplyBullet;
            
            /// <summary>
            /// Originally defined as: <c><![CDATA[int8 rfid]]></c>
            /// </summary>
            public sbyte Rfid;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.FriendsHero);
                __hashCode.Add(this.FriendsEngineer);
                __hashCode.Add(this.FriendsInfantryIii);
                __hashCode.Add(this.FriendsInfantryIv);
                __hashCode.Add(this.FriendsInfantryV);
                __hashCode.Add(this.FriendsSentry);
                __hashCode.Add(this.EnemiesHero);
                __hashCode.Add(this.EnemiesEngineer);
                __hashCode.Add(this.EnemiesInfantryIii);
                __hashCode.Add(this.EnemiesInfantryIv);
                __hashCode.Add(this.EnemiesInfantryV);
                __hashCode.Add(this.EnemiesSentry);
                __hashCode.Add(this.FriendsOutpostHp);
                __hashCode.Add(this.EnemiesOutpostHp);
                __hashCode.Add(this.FriendsBaseHp);
                __hashCode.Add(this.EnemiesBaseHp);
                __hashCode.Add(this.Bullet);
                __hashCode.Add(this.SupplyBullet);
                __hashCode.Add(this.Rfid);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::Rosidl.Messages.RmcsMap.GameStatus.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Blittable native sequence structure for <c>rmcs_map/msg/GameStatus</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("rmcs_map__rosidl_generator_c", EntryPoint = "rmcs_map__msg__GameStatus__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.3.2+da40d8cd913b1d7f1523f4fd2ce6a86ea7d47c2e")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::Rosidl.Messages.RmcsMap.GameStatus.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
