<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <InvariantGlobalization>true</InvariantGlobalization>
        <OptimizationPreference>Speed</OptimizationPreference>
        
        <PublishDir>$(SolutionDir)\.test\BenchMarks\$(ProjectName)\$(Configuration)</PublishDir>

        
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Kernel.Core\Kernel.Core.csproj"/>
    </ItemGroup>

</Project>
