#! /bin/bash
sudo apt remove -y "dotnet-*"
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --version 9.0.304
rm ./dotnet-install.sh
sudo ln -s  ~/.dotnet/dotnet  /bin/dotnet