//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace TlarcRosBridge.Infrastructure.Messages.Visualization
{
    /// <summary>
    /// Message interface definition for <c>visualization_msgs/msg/ImageMarker</c>.
    /// </summary>
    [global::Rosidl.Runtime.TypeSupportAttribute("visualization_msgs/msg/ImageMarker")]
    public unsafe partial class ImageMarker : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static string TypeSupportName => "visualization_msgs/msg/ImageMarker";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__ImageMarker")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="ImageMarker"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='header'>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>
        /// </param>
        /// <param name='ns'>
        /// Namespace which is used with the id to form a unique id.
        /// <para>(originally defined as: <c><![CDATA[string ns]]></c>)</para>
        /// </param>
        /// <param name='id'>
        /// Unique id within the namespace.
        /// <para>(originally defined as: <c><![CDATA[int32 id]]></c>)</para>
        /// </param>
        /// <param name='type'>
        /// One of the above types, e.g. CIRCLE, LINE_STRIP, etc.
        /// <para>(originally defined as: <c><![CDATA[int32 type]]></c>)</para>
        /// </param>
        /// <param name='action'>
        /// Either ADD or REMOVE.
        /// <para>(originally defined as: <c><![CDATA[int32 action]]></c>)</para>
        /// </param>
        /// <param name='position'>
        /// Two-dimensional coordinate position, in pixel-coordinates.
        /// <para>(originally defined as: <c><![CDATA[geometry_msgs/msg/Point position]]></c>)</para>
        /// </param>
        /// <param name='scale'>
        /// The scale of the object, e.g. the diameter for a CIRCLE.
        /// <para>(originally defined as: <c><![CDATA[float32 scale]]></c>)</para>
        /// </param>
        /// <param name='outlineColor'>
        /// The outline color of the marker.
        /// <para>(originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA outline_color]]></c>)</para>
        /// </param>
        /// <param name='filled'>
        /// Whether or not to fill in the shape with color.
        /// <para>(originally defined as: <c><![CDATA[uint8 filled]]></c>)</para>
        /// </param>
        /// <param name='fillColor'>
        /// Fill color; in the range: [0.0-1.0]
        /// <para>(originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA fill_color]]></c>)</para>
        /// </param>
        /// <param name='lifetime'>
        /// How long the object should last before being automatically deleted.
        /// 0 indicates forever.
        /// <para>(originally defined as: <c><![CDATA[builtin_interfaces/msg/Duration lifetime]]></c>)</para>
        /// </param>
        /// <param name='points'>
        /// Coordinates in 2D in pixel coords. Used for LINE_STRIP, LINE_LIST, POINTS, etc.
        /// <para>(originally defined as: <c><![CDATA[geometry_msgs/msg/Point[] points]]></c>)</para>
        /// </param>
        /// <param name='outlineColors'>
        /// The color for each line, point, etc. in the points field.
        /// <para>(originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA[] outline_colors]]></c>)</para>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public ImageMarker(
            global::TlarcRosBridge.Infrastructure.Messages.Std.Header? @header = null,
            string @ns = "",
            int @id = 0,
            int @type = 0,
            int @action = 0,
            global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point? @position = null,
            float @scale = 0f,
            global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA? @outlineColor = null,
            byte @filled = 0,
            global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA? @fillColor = null,
            global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration? @lifetime = null,
            global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point[]? @points = null,
            global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA[]? @outlineColors = null
        )
        {
            Header = @header ?? new global::TlarcRosBridge.Infrastructure.Messages.Std.Header();
            Ns = @ns;
            Id = @id;
            Type = @type;
            Action = @action;
            Position = @position ?? new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point();
            Scale = @scale;
            OutlineColor = @outlineColor ?? new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA();
            Filled = @filled;
            FillColor = @fillColor ?? new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA();
            Lifetime = @lifetime ?? new global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration();
            Points = @points ?? global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point>();
            OutlineColors = @outlineColors ?? global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA>();
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="ImageMarker"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public ImageMarker(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header = new global::TlarcRosBridge.Infrastructure.Messages.Std.Header(in priv.Header, textEncoding);
            this.Ns = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.Ns.AsSpan(), textEncoding);
            this.Id = priv.Id;
            this.Type = priv.Type;
            this.Action = priv.Action;
            this.Position = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point(in priv.Position, textEncoding);
            this.Scale = priv.Scale;
            this.OutlineColor = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA(in priv.OutlineColor, textEncoding);
            this.Filled = priv.Filled;
            this.FillColor = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA(in priv.FillColor, textEncoding);
            this.Lifetime = new global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration(in priv.Lifetime, textEncoding);
        
            this.Points = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point[priv.Points.Size];
            var Points_span = priv.Points.AsSpan();
            for (int __i = 0; __i < this.Points.Length; __i++)
            {
                this.Points[__i] = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point(in Points_span[__i], textEncoding);
            }
        
            this.OutlineColors = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA[priv.OutlineColors.Size];
            var OutlineColors_span = priv.OutlineColors.AsSpan();
            for (int __i = 0; __i < this.OutlineColors.Length; __i++)
            {
                this.OutlineColors[__i] = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA(in OutlineColors_span[__i], textEncoding);
            }
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="ImageMarker"/> with fields initialized to default values.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public ImageMarker()
        {
            Header = new global::TlarcRosBridge.Infrastructure.Messages.Std.Header();
            Ns = "";
            Id = 0;
            Type = 0;
            Action = 0;
            Position = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point();
            Scale = 0f;
            OutlineColor = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA();
            Filled = 0;
            FillColor = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA();
            Lifetime = new global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration();
            Points = global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point>();
            OutlineColors = global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA>();
        }
        
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 CIRCLE = 0]]></c>
        /// </summary>
        public const int CIRCLE = 0;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 LINE_STRIP = 1]]></c>
        /// </summary>
        public const int LINE_STRIP = 1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 LINE_LIST = 2]]></c>
        /// </summary>
        public const int LINE_LIST = 2;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 POLYGON = 3]]></c>
        /// </summary>
        public const int POLYGON = 3;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 POINTS = 4]]></c>
        /// </summary>
        public const int POINTS = 4;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 ADD = 0]]></c>
        /// </summary>
        public const int ADD = 0;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[int32 REMOVE = 1]]></c>
        /// </summary>
        public const int REMOVE = 1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Std.Header Header { get; set; }
        
        /// <summary>
        /// Namespace which is used with the id to form a unique id.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[string ns]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public string Ns { get; set; }
        
        /// <summary>
        /// Unique id within the namespace.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[int32 id]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public int Id { get; set; }
        
        /// <summary>
        /// One of the above types, e.g. CIRCLE, LINE_STRIP, etc.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[int32 type]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public int Type { get; set; }
        
        /// <summary>
        /// Either ADD or REMOVE.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[int32 action]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public int Action { get; set; }
        
        /// <summary>
        /// Two-dimensional coordinate position, in pixel-coordinates.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Point position]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point Position { get; set; }
        
        /// <summary>
        /// The scale of the object, e.g. the diameter for a CIRCLE.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 scale]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public float Scale { get; set; }
        
        /// <summary>
        /// The outline color of the marker.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA outline_color]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA OutlineColor { get; set; }
        
        /// <summary>
        /// Whether or not to fill in the shape with color.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 filled]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public byte Filled { get; set; }
        
        /// <summary>
        /// Fill color; in the range: [0.0-1.0]
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA fill_color]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA FillColor { get; set; }
        
        /// <summary>
        /// How long the object should last before being automatically deleted.
        /// 0 indicates forever.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[builtin_interfaces/msg/Duration lifetime]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration Lifetime { get; set; }
        
        /// <summary>
        /// Coordinates in 2D in pixel coords. Used for LINE_STRIP, LINE_LIST, POINTS, etc.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Point[] points]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point[] Points { get; set; }
        
        /// <summary>
        /// The color for each line, point, etc. in the points field.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA[] outline_colors]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA[] OutlineColors { get; set; }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header.WriteTo(ref priv.Header, textEncoding);
            priv.Ns.CopyFrom(this.Ns, textEncoding);
            priv.Id = this.Id;
            priv.Type = this.Type;
            priv.Action = this.Action;
            this.Position.WriteTo(ref priv.Position, textEncoding);
            priv.Scale = this.Scale;
            this.OutlineColor.WriteTo(ref priv.OutlineColor, textEncoding);
            priv.Filled = this.Filled;
            this.FillColor.WriteTo(ref priv.FillColor, textEncoding);
            this.Lifetime.WriteTo(ref priv.Lifetime, textEncoding);
            
            priv.Points = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point.PrivSequence(this.Points.Length);
            var Points_span = priv.Points.AsSpan();
            for (int __i = 0; __i < this.Points.Length; __i++)
            {
                this.Points[__i].WriteTo(ref Points_span[__i], textEncoding);
            }
            
            priv.OutlineColors = new global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA.PrivSequence(this.OutlineColors.Length);
            var OutlineColors_span = priv.OutlineColors.AsSpan();
            for (int __i = 0; __i < this.OutlineColors.Length; __i++)
            {
                this.OutlineColors[__i].WriteTo(ref OutlineColors_span[__i], textEncoding);
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new ImageMarker(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Blittable native structure for <c>visualization_msgs/msg/ImageMarker</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>
            /// </summary>
            public global::TlarcRosBridge.Infrastructure.Messages.Std.Header.Priv Header;
            
            /// <summary>
            /// Namespace which is used with the id to form a unique id.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[string ns]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.CString Ns;
            
            /// <summary>
            /// Unique id within the namespace.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[int32 id]]></c>
            /// </remarks>
            public int Id;
            
            /// <summary>
            /// One of the above types, e.g. CIRCLE, LINE_STRIP, etc.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[int32 type]]></c>
            /// </remarks>
            public int Type;
            
            /// <summary>
            /// Either ADD or REMOVE.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[int32 action]]></c>
            /// </remarks>
            public int Action;
            
            /// <summary>
            /// Two-dimensional coordinate position, in pixel-coordinates.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Point position]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point.Priv Position;
            
            /// <summary>
            /// The scale of the object, e.g. the diameter for a CIRCLE.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 scale]]></c>
            /// </remarks>
            public float Scale;
            
            /// <summary>
            /// The outline color of the marker.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA outline_color]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA.Priv OutlineColor;
            
            /// <summary>
            /// Whether or not to fill in the shape with color.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[uint8 filled]]></c>
            /// </remarks>
            public byte Filled;
            
            /// <summary>
            /// Fill color; in the range: [0.0-1.0]
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA fill_color]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA.Priv FillColor;
            
            /// <summary>
            /// How long the object should last before being automatically deleted.
            /// 0 indicates forever.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[builtin_interfaces/msg/Duration lifetime]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Builtin.Duration.Priv Lifetime;
            
            /// <summary>
            /// Coordinates in 2D in pixel coords. Used for LINE_STRIP, LINE_LIST, POINTS, etc.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Point[] points]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Point.PrivSequence Points;
            
            /// <summary>
            /// The color for each line, point, etc. in the points field.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[std_msgs/msg/ColorRGBA[] outline_colors]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Std.ColorRGBA.PrivSequence OutlineColors;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.Header);
                __hashCode.Add(this.Ns);
                __hashCode.Add(this.Id);
                __hashCode.Add(this.Type);
                __hashCode.Add(this.Action);
                __hashCode.Add(this.Position);
                __hashCode.Add(this.Scale);
                __hashCode.Add(this.OutlineColor);
                __hashCode.Add(this.Filled);
                __hashCode.Add(this.FillColor);
                __hashCode.Add(this.Lifetime);
                __hashCode.Add(this.Points);
                __hashCode.Add(this.OutlineColors);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::TlarcRosBridge.Infrastructure.Messages.Visualization.ImageMarker.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Blittable native sequence structure for <c>visualization_msgs/msg/ImageMarker</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__ImageMarker__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::TlarcRosBridge.Infrastructure.Messages.Visualization.ImageMarker.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
