//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace TlarcRosBridge.Infrastructure.Messages.Visualization
{
    /// <summary>
    /// Time/frame info.
    /// If header.time is set to 0, the marker will be retransformed into
    /// its frame on each timestep. You will receive the pose feedback
    /// in the same frame.
    /// Otherwise, you might receive feedback in a different frame.
    /// For rviz, this will be the current 'fixed frame' set by the user.
    /// </summary>
    /// <remarks>
    /// Message interface definition for <c>visualization_msgs/msg/InteractiveMarker</c>.
    /// </remarks>
    [global::Rosidl.Runtime.TypeSupportAttribute("visualization_msgs/msg/InteractiveMarker")]
    public unsafe partial class InteractiveMarker : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static string TypeSupportName => "visualization_msgs/msg/InteractiveMarker";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__InteractiveMarker")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="InteractiveMarker"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='header'>
        /// Time/frame info.
        /// If header.time is set to 0, the marker will be retransformed into
        /// its frame on each timestep. You will receive the pose feedback
        /// in the same frame.
        /// Otherwise, you might receive feedback in a different frame.
        /// For rviz, this will be the current 'fixed frame' set by the user.
        /// <para>(originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>)</para>
        /// </param>
        /// <param name='pose'>
        /// Initial pose. Also, defines the pivot point for rotations.
        /// <para>(originally defined as: <c><![CDATA[geometry_msgs/msg/Pose pose]]></c>)</para>
        /// </param>
        /// <param name='name'>
        /// Identifying string. Must be globally unique in
        /// the topic that this message is sent through.
        /// <para>(originally defined as: <c><![CDATA[string name]]></c>)</para>
        /// </param>
        /// <param name='description'>
        /// Short description (< 40 characters).
        /// <para>(originally defined as: <c><![CDATA[string description]]></c>)</para>
        /// </param>
        /// <param name='scale'>
        /// Scale to be used for default controls (default=1).
        /// <para>(originally defined as: <c><![CDATA[float32 scale]]></c>)</para>
        /// </param>
        /// <param name='menuEntries'>
        /// All menu and submenu entries associated with this marker.
        /// <para>(originally defined as: <c><![CDATA[visualization_msgs/msg/MenuEntry[] menu_entries]]></c>)</para>
        /// </param>
        /// <param name='controls'>
        /// List of controls displayed for this marker.
        /// <para>(originally defined as: <c><![CDATA[visualization_msgs/msg/InteractiveMarkerControl[] controls]]></c>)</para>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public InteractiveMarker(
            global::TlarcRosBridge.Infrastructure.Messages.Std.Header? @header = null,
            global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose? @pose = null,
            string @name = "",
            string @description = "",
            float @scale = 0f,
            global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry[]? @menuEntries = null,
            global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl[]? @controls = null
        )
        {
            Header = @header ?? new global::TlarcRosBridge.Infrastructure.Messages.Std.Header();
            Pose = @pose ?? new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose();
            Name = @name;
            Description = @description;
            Scale = @scale;
            MenuEntries = @menuEntries ?? global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry>();
            Controls = @controls ?? global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl>();
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="InteractiveMarker"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public InteractiveMarker(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header = new global::TlarcRosBridge.Infrastructure.Messages.Std.Header(in priv.Header, textEncoding);
            this.Pose = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose(in priv.Pose, textEncoding);
            this.Name = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.Name.AsSpan(), textEncoding);
            this.Description = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.Description.AsSpan(), textEncoding);
            this.Scale = priv.Scale;
        
            this.MenuEntries = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry[priv.MenuEntries.Size];
            var MenuEntries_span = priv.MenuEntries.AsSpan();
            for (int __i = 0; __i < this.MenuEntries.Length; __i++)
            {
                this.MenuEntries[__i] = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry(in MenuEntries_span[__i], textEncoding);
            }
        
            this.Controls = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl[priv.Controls.Size];
            var Controls_span = priv.Controls.AsSpan();
            for (int __i = 0; __i < this.Controls.Length; __i++)
            {
                this.Controls[__i] = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl(in Controls_span[__i], textEncoding);
            }
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="InteractiveMarker"/> with fields initialized to default values.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public InteractiveMarker()
        {
            Header = new global::TlarcRosBridge.Infrastructure.Messages.Std.Header();
            Pose = new global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose();
            Name = "";
            Description = "";
            Scale = 0f;
            MenuEntries = global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry>();
            Controls = global::System.Array.Empty<global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl>();
        }
        
        
        /// <summary>
        /// Time/frame info.
        /// If header.time is set to 0, the marker will be retransformed into
        /// its frame on each timestep. You will receive the pose feedback
        /// in the same frame.
        /// Otherwise, you might receive feedback in a different frame.
        /// For rviz, this will be the current 'fixed frame' set by the user.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Std.Header Header { get; set; }
        
        /// <summary>
        /// Initial pose. Also, defines the pivot point for rotations.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Pose pose]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose Pose { get; set; }
        
        /// <summary>
        /// Identifying string. Must be globally unique in
        /// the topic that this message is sent through.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[string name]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public string Name { get; set; }
        
        /// <summary>
        /// Short description (< 40 characters).
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[string description]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public string Description { get; set; }
        
        /// <summary>
        /// Scale to be used for default controls (default=1).
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 scale]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public float Scale { get; set; }
        
        /// <summary>
        /// All menu and submenu entries associated with this marker.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[visualization_msgs/msg/MenuEntry[] menu_entries]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry[] MenuEntries { get; set; }
        
        /// <summary>
        /// List of controls displayed for this marker.
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[visualization_msgs/msg/InteractiveMarkerControl[] controls]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl[] Controls { get; set; }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header.WriteTo(ref priv.Header, textEncoding);
            this.Pose.WriteTo(ref priv.Pose, textEncoding);
            priv.Name.CopyFrom(this.Name, textEncoding);
            priv.Description.CopyFrom(this.Description, textEncoding);
            priv.Scale = this.Scale;
            
            priv.MenuEntries = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry.PrivSequence(this.MenuEntries.Length);
            var MenuEntries_span = priv.MenuEntries.AsSpan();
            for (int __i = 0; __i < this.MenuEntries.Length; __i++)
            {
                this.MenuEntries[__i].WriteTo(ref MenuEntries_span[__i], textEncoding);
            }
            
            priv.Controls = new global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl.PrivSequence(this.Controls.Length);
            var Controls_span = priv.Controls.AsSpan();
            for (int __i = 0; __i < this.Controls.Length; __i++)
            {
                this.Controls[__i].WriteTo(ref Controls_span[__i], textEncoding);
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new InteractiveMarker(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Time/frame info.
        /// If header.time is set to 0, the marker will be retransformed into
        /// its frame on each timestep. You will receive the pose feedback
        /// in the same frame.
        /// Otherwise, you might receive feedback in a different frame.
        /// For rviz, this will be the current 'fixed frame' set by the user.
        /// </summary>
        /// <remarks>
        /// Blittable native structure for <c>visualization_msgs/msg/InteractiveMarker</c>.
        /// </remarks>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Time/frame info.
            /// If header.time is set to 0, the marker will be retransformed into
            /// its frame on each timestep. You will receive the pose feedback
            /// in the same frame.
            /// Otherwise, you might receive feedback in a different frame.
            /// For rviz, this will be the current 'fixed frame' set by the user.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[std_msgs/msg/Header header]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Std.Header.Priv Header;
            
            /// <summary>
            /// Initial pose. Also, defines the pivot point for rotations.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[geometry_msgs/msg/Pose pose]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Geometry.Pose.Priv Pose;
            
            /// <summary>
            /// Identifying string. Must be globally unique in
            /// the topic that this message is sent through.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[string name]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.CString Name;
            
            /// <summary>
            /// Short description (< 40 characters).
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[string description]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.CString Description;
            
            /// <summary>
            /// Scale to be used for default controls (default=1).
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 scale]]></c>
            /// </remarks>
            public float Scale;
            
            /// <summary>
            /// All menu and submenu entries associated with this marker.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[visualization_msgs/msg/MenuEntry[] menu_entries]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Visualization.MenuEntry.PrivSequence MenuEntries;
            
            /// <summary>
            /// List of controls displayed for this marker.
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[visualization_msgs/msg/InteractiveMarkerControl[] controls]]></c>
            /// </remarks>
            public global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarkerControl.PrivSequence Controls;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.Header);
                __hashCode.Add(this.Pose);
                __hashCode.Add(this.Name);
                __hashCode.Add(this.Description);
                __hashCode.Add(this.Scale);
                __hashCode.Add(this.MenuEntries);
                __hashCode.Add(this.Controls);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarker.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Time/frame info.
        /// If header.time is set to 0, the marker will be retransformed into
        /// its frame on each timestep. You will receive the pose feedback
        /// in the same frame.
        /// Otherwise, you might receive feedback in a different frame.
        /// For rviz, this will be the current 'fixed frame' set by the user.
        /// </summary>
        /// <remarks>
        /// Blittable native sequence structure for <c>visualization_msgs/msg/InteractiveMarker</c>.
        /// </remarks>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("visualization_msgs__rosidl_generator_c", EntryPoint = "visualization_msgs__msg__InteractiveMarker__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ros2cs", "1.4.0+866072750999979fa04a21d1d2f84d5346ef2c35")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::TlarcRosBridge.Infrastructure.Messages.Visualization.InteractiveMarker.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
